name: cd&cd

on:
  push:
    branches:
      - lambda-tf

env:
  AWS_REGION: us-east-1

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'aws/demo-aws-lambda/nodejs-app/'
    strategy:
      matrix:
        node-version: [17.x]

    if: github.ref == 'refs/heads/lambda-tf'
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci

    - name: Upload app node built as artifact
      uses: actions/upload-artifact@v2
      with:
        name: appcode
        path: aws/demo-aws-lambda/nodejs-app/  # Defining . doesnot work
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/lambda-tf'
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Download app node
      uses: actions/download-artifact@v2
      with:
        name: appcode
        path: aws/demo-aws-lambda/nodeApp/

    - uses: hashicorp/setup-terraform@v2
      env:
        terraform_version: 1.2.5
    - name: terraform init
      id: init
      run: terraform init
      working-directory: aws/demo-aws-lambda/
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: terraform plan
      id: plan
      run: terraform plan
      working-directory: aws/demo-aws-lambda/
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: terraform apply
      id: apply
      run: terraform apply  -auto-approve
      working-directory: aws/demo-aws-lambda/
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}




