
  name: Main Workflow
  on: push

  jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: ls
              run: |
                ls -la
                ls ./.github/workflows/
            - name: Install dependencies
              uses: "./.github/template/deploy"
              with:
                version: v1.0.0
                namespace: "stage"
    call-workflow-2-in-local-repo:
      uses:  ./.github/template/reusable/workflow-B.yml