
  name: Main Workflow
  on: push

  jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: ls
              run: |
                ls -l
            - name: Install dependencies
              uses: ./.github/workflows/template-a.yml
              with:
                foo: bar 