
  name: Main Workflow
  on:
    push:
      branches:
        - testing_actions

  jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: ls
              run: |
                ls -la
                ls ./.github/workflows/
            - name: Install dependencies
              uses: "./.github/template/deploy"
              with:
                version: v1.0.0
                namespace: "stage"
            - name: Wait for Approval
              uses: trstringer/manual-approval@v1
              id: manual_approval

    call-workflow-2-in-local-repo:
      uses:  ./.github/workflows/workflow-B.yml
      with:
        config-path: "config-path"
