name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string


jobs:
  triage:
    environment: stage
    runs-on: ubuntu-latest
    steps:
    - name: test title
      run: |
        echo "test"
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        project_id: esparta86project
        # project_id: ${{ inputs.project_id }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}